#!/usr/bin/env php
<?php
define('CONSOLE_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$process = new Symfony\Component\Process\Process(array('php', './vendor/bin/phpunit'));
$process->start();

foreach ($process as $type => $data) {
    if ($process::OUT === $type) {
        echo $data;
    } else { // $process::ERR === $type
        echo $data;
    }
}